version: '3'

services:
  sma-pvoutput:
    image: sma-pvoutput:latest
    container_name: sma-pvoutput
    environment:
      - influx_ip=<192.168.1.3>
      - influx_port=<8086>
      - influx_db=<SMA>
      - influx_user=<user>
      - influx_pw=<pw>
      - pv_consumption=0
      - pv_sid=<PV Output System ID>
      - pv_key=<PV OutPut API Key>
      - TZ=Europe/Berlin
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    restart: unless-stopped
