#!/usr/bin/with-contenv bash

python3 -u /pvoutput.py --pv_key $pv_key --pv_sid $pv_sid --pv_consumption $pv_consumption --influx_ip $influx_ip --influx_port $influx_port --influx_user $influx_user --influx_pw $influx_pw --influx_db $influx_db
